//
//  PathRenderer.swift
//  DrawTesting
//
//  Created by Dante Broggi on 9/24/17.
//  Copyright © 2017 Dante Broggi. All rights reserved.
//

///A path is generated by a sequence of lines / curves
public protocol PathRenderer {
    typealias Graphics = Space.Graphics
    associatedtype Space: DrawSpace
    
    mutating func line(to point: Space.Point)
    mutating func quadraticCurve(to end: Space.Point, control: Space.Point)
    mutating func cubicCurve(to end: Space.Point, control1: Space.Point, control2: Space.Point)
    mutating func lines(between points: [Space.Point])
    
    //    @available(deprecated: "Angles are obsolete, use spreads instead")
//        mutating func relativeArc(center: Space.Point, radius: Space.LinearDisplacement,
//                                  startAngle: Space.Angle, delta: Space.Angle.BaseNumberType)
    
    //    @available(deprecated: "Angles are obsolete, use spreads instead")
//        mutating func arc(center: Space.Point, radius: Space.LinearDisplacement,
//                          startAngle: Space.Angle, endAngle: Space.Angle, clockwise: Bool)
    mutating func arc(tangent1End: Space.Point, tangent2End: Space.Point, radius: Space.LinearDisplacement)
}
